apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-operator
subjects:
  - kind: ServiceAccount
    name: custom-metrics-operator
    namespace: kubesphere-monitoring-system