apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: custom-metrics-operator
  name: custom-metrics-operator
  namespace: kubesphere-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: custom-metrics-operator
  template:
    metadata:
      labels:
        k8s-app: custom-metrics-operator
    spec:
      containers:
        - args:
            - --ignored-namespaces=kubesphere-monitoring-system
          image: dockerhub.qingcloud.com/loganhuang/custom-metrics-operator:latest
          imagePullPolicy: Always
          name: custom-metrics-operator
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: custom-metrics-operator